### ISSUE TITLE
What exactly does the "AssetManager" do?

### ISSUE THREAD

**Issue by h1-yena** [itzi97/itzicpp-engine#2]
Given that code should follow the single responsibility principle, I would advice you try to take apart your class AssetManager to see whether it follows it or is in dire need of splitting.

Ask yourself: What does that class do?

If you name more than one thing, then the SRP is violated and you should probably define it a bit better.

**Comment by itzi97** [comment]
![image](https://user-images.githubusercontent.com/56316427/85257743-9f453c00-b466-11ea-85df-f0e78adccc6f.png)

The asset manager is an interface that the game uses to manage different resources, it calls other managers to do this and stores different resource objects like textures and such within it. So far there is only the textures that the asset manager manages, but it will also manage sounds and such. I guess in a way the SRP is violated because we're storing assets of different types, but they're all assets. I'll see if the functionality needs to be divided into different classes once i add different asset types (if they require the assetManager to do different things which shouldn't be the case), if not, i'll keep it this way.
